services:
  - type: web
    name: label-studio-eval
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/llm_evaluation
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: LABEL_STUDIO_HOST
        value: 0.0.0.0
      - key: LABEL_STUDIO_PORT
        value: 8080
